### ISSUE TITLE
Problem open pbi 

### ISSUE THREAD

**Issue by zic04** [mddazure/vnet-flow-logs-powerbi#1]
Hello,

Error open file : 

https://learn.microsoft.com/en-us/power-bi/enterprise/service-security-enable-data-sensitivity-labels#licensing-and-requirements

![image](https://github.com/mddazure/vnet-flow-logs-powerbi/assets/52179053/7efdc3a0-8617-4b15-b2ea-028aee5fc127)

**Comment by mddazure** [comment]
Use PowerBI_VNETFlowLogs_Storage_Template_public.pbit
